### ISSUE TITLE
Ways to stop a running Session from within

### ISSUE THREAD

**Issue by martinthenext** [tkim/emsx_api_repository#1]
Hi, I have a pretty generic question about the EMSX code, thought I'd ask it here in case somebody else finds it useful.

The workflow of all the EMSX examples I looked at seems to be:

1. Create an event handler object with a function to process events
2. Create a Session object and pass the event handler as a parameter
3. `startAsync` the Session to run in a separate thread

The Session thread keeps running until `stop` or `stopAsync` is called on the session object, which can only be done in the main thread. In C++ examples the Session thread [seems to keep running](https://github.com/tkim/emsx_api_repository/blob/c5267922cb63edf343817933cf32c442497427c7/EMSXFullSet_C%2B%2B/CreateOrderAndRouteEx.cpp#L387) until a keyboard interrupt. In Python examples, you use a global variable `bEnd` that [you set](https://github.com/tkim/emsx_api_repository/blob/c5267922cb63edf343817933cf32c442497427c7/EMSXFullSet_Python/CreateOrderAndRouteEx.py#L218) from within a Session thread to prompt the main thread to `stop` the Session. 

I can see how many users would want to stop the Session as soon as they received all the necessary data, not on keyboard interrupt. Global variable `bEnd` in case of Python provides some solution, but the mechanics of multi-thread access to this variable (given blpapi bind to C++ binaries) is unclear. Is there some other way to `stop` the Session from within or communicate with the main thread?

Thank you.

**Comment by tkim** [comment]
Hi, the EMSX API follows the EMSX<GO> function workflow within the Bloomberg terminal. 

In real-life scenario the listener for orders and routes should be up at all times as the broker execution isn't necessarily a timed event and thus throughout the life cycle of an order, both the execution messages along with other state events will come back through this subscription channel. 

The sample here is really to illustrate how each EMSX features work and not meant to be used in production trading environment. 

Thanks
